### ISSUE TITLE
[Enhancement][Track] Release kclvm crates to crates.io

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#1193]
## Tasks

+ [x] Add llvm feature for the kclvm_compiler crate. https://github.com/kcl-lang/kcl/pull/1198
+ [x] Release the latest `compiler_base` crate to the crates.io #1204
+ [x] Update the `compiler_base` deps of all kclvm crates. #1204 
+ [x] Release the kclvm crate to the crates.io. We can add kcl deps using `cargo add --git https://github.com/kcl-lang/kcl kclvm-parser` or `cargo add --git https://github.com/kcl-lang/kcl kclvm-api`

**Comment by Peefy** [comment]
Closed by #1198 and #1204
