### ISSUE TITLE
[Enhancement][Track] KCL VSCode IDE extension and lsp enhancement

### ISSUE THREAD

**Issue by He1pa** [kcl-lang/kcl#524]
## Enhancement

TODO List

+ [x] Semantic highlighting
+ [x] daily release ci 
+ [x]  Different completion kinds for string variables and literals #963 

![image](https://github.com/kcl-lang/kcl/assets/22744597/7c6a4910-e5a4-4829-8594-c2580473c44b)

![image](https://github.com/kcl-lang/kcl/assets/22744597/d0a32547-514c-4d33-bea3-993dcfc5e947)

+ [x] Wrong schema entry completion items for internal schema definition in the schema.

![image](https://github.com/kcl-lang/kcl/assets/22744597/e25f8ebe-57b0-4c10-a583-30f8f86a3e52)

+ [x] Support completion for more complex selector and subscript expression syntax, e.g, `kind[0].lower() # kind[0] is the string type`

```python
schema Person:
    names: [str]

a = (Person{
    names = ["123"]
}.names)?[0]
```

feat:

- [x] More precise lookup and goto definition
  + [x] More precise lookup definitions in the symbol table #606 
  + [x] Divide Ident into different definitions and jump to different locations, e.g., for `a.b.c`, find definition of `a`,`b` and `c`, instead of `a.b.c` #608 
- [x] hover enhance: doc parse and better organization of presentation content  #621 
- [x] diagnostics enhance for conflict attr #646 
- [x] Intelligent perception display of function icons and documents for members of str type.
- [x] kcl-language-server version show versions
- [x] refactor functions:
  - [x] kcl schema/attribute/function/import auto rename.

- [x] The completion of map key.
- [x] Additional error plugin installation dependencies or instructions.
https://github.com/KusionStack/kcl-lang.io/pull/96
![image](https://github.com/KusionStack/kcl/assets/22744597/429fc790-cbdf-480d-9b3e-caa71fe6b47b)
- [x] Hover for SchemaAttr AST Node
- [x] Go to definition for lambda arguments

```python
lambda a: int {
    b = a # Go to definition feat for `a` in `b = a` is not work.
}
```

- [x] kpm package import completion
- [x] completion on the right side value of the assignment statement
- [x] completion on the built-in package import
- [x] completion on the parameter list of the built-in functions
- [x] Right click for run/format/...
  - [x] fmt #680  #682
- [x] completion for attr, var, pkg name #614 
  - [x] completion on newline in braces: the alternative attribute list should be displayed on initializing schema instance
- [x] quick fix #652 
- [x] diagnostics enhance 
  + #638 
  + #646 
  + #652 
- [x] support find reference #712
test:
+ [x] e2e test #700 
+ [x] integration test of konfig #714

release:
https://github.com/kcl-lang/kcl/issues/602
+ [x] kcl lsp version #730 
+ [x] install with package manager, e.g., homebrew

bugfix:

- [x] literal str methods completion #593 
- [x] import pkg completion
- [x] Syntax incompatibility upgrades lead to errors(`:` and `=` in base and stack)
- [x] Goto definition failed in main.k(Can't find ast node from position due to config merge(preprocess in resolver)) #675 
- [x] Conflict between pkg var and for loop local var.
- [x] Schema document only contains the header not include the schema attr. #621 
- [x] Dot completion #614 
![image](https://github.com/KusionStack/KCLVM/assets/22744597/487fe930-4b2e-4cc3-a9d0-ac825fd12ec9)
- [x] Attr position err #674 
![image](https://github.com/kcl-lang/kcl/assets/56333845/1bd2fb4a-62a0-405c-9840-c07f38d3b887)
- [x] Unused import #686
![image](https://github.com/kcl-lang/kcl/assets/56333845/0f51dca3-817f-4112-b6d1-6a44520abc44)
- [x] config expr complete
![image](https://github.com/kcl-lang/kcl/assets/56333845/d34c663c-b42f-421f-905d-64febade7d63)
- [x] ConfigEntry and ConfigIfEntry #687 
```
capabilities = option("params").capabilities or ["SETUID", "SETFCAP"]
items = [item | {
    if item.kind == "Pod":
        spec.containers: [{
            "securityContext": {"capabilities": {"add" += [c] if c not in (container?.securityContext?.capabilities?.drop or []) else [] for c in capabilities}}
        } for container in item.spec.containers]
} for item in option("items")]

params = option("params")
toMatch = params.toMatch
toAdd = params.toAdd
items = [item | {
   # If all annotations are matched, patch more annotations
   if all key, value in toMatch {
      item.metadata.annotations[key] == value
   }:
       metadata.annotations: toAdd
} for item in option("items")]
```
+ [x] #758

```python
a = "".capitalize() # The function has hover info
b = a.capitalize() # The function has not hover info
```

releated issues
+ https://github.com/kcl-lang/kcl/issues/634
+ https://github.com/kcl-lang/kcl/issues/635

+ [x] The variable to the right of a continuous logical expression `a and b` `a and b or c` does not have hovering information.

![image](https://github.com/kcl-lang/kcl/assets/22744597/cf53847b-4c22-4df8-9e30-d528c4587f5e)

+ [x] Wrong hover item for the package name. expected `app` got `app:`

![image](https://github.com/kcl-lang/kcl/assets/22744597/b8bc4efb-4ddf-47fb-af4e-189e0d63c4ab)

+ [x] Completion for the optional chain operator `?.`

+ [x] Wrong completion item for check colon `:`  https://github.com/kcl-lang/kcl/pull/946

![image](https://github.com/kcl-lang/kcl/assets/22744597/320b1bbc-dc14-4eff-a6d7-a1e850054650)

+ [x] Wrong schema entry completion items for internal schema definition in the schema.

![image](https://github.com/kcl-lang/kcl/assets/22744597/e25f8ebe-57b0-4c10-a583-30f8f86a3e52)

+ [x] Support completion for more complex selector and subscript expression syntax, e.g, `kind[0].lower() # kind[0] is the string type`

```python
schema Person:
    names: [str]

a = (Person{
    names = ["123"]
}.names)?[0]
```

+ [x] https://github.com/kcl-lang/kcl/pull/992

![image](https://github.com/kcl-lang/kcl/assets/22744597/c7f0198d-76fa-49ac-a5e6-0083a7a0357d)

+ [x] No hover information for the attribute `strategy` after the if config block.
https://github.com/kcl-lang/kcl/pull/1027

```python
import k8s.api.apps.v1 as appsv1
import k8s.api.core.v1 as corev1
import config

deployment = appsv1.Deployment {
    metadata: config.metadata
    spec: appsv1.DeploymentSpec {
        if config.autoscaling.enabled:
            replicas = config.replicas
        strategy = {
            type =  "RollingUpdate"
            rollingUpdate.maxUnavailable = "50%"
        }
    }
}

```

+ [x] Wrong completion for the schema check `:` char
https://github.com/kcl-lang/kcl/pull/1057
![image](https://github.com/kcl-lang/kcl/assets/22744597/81681074-4a5b-4221-acdb-456a6d2abb26)

+ [x] No completion for the schema check `?.` char
https://github.com/kcl-lang/kcl/pull/1030

![image](https://github.com/kcl-lang/kcl/assets/22744597/ef4d7181-5939-437f-b333-53977c4fe03b)
![image](https://github.com/kcl-lang/kcl/assets/22744597/bdf97f08-705c-4146-ae51-7c22784a1c6c)

+ [x] Wrong completion items for multiple different char after `.` e.g. `c`, `o`, `co`

![image](https://github.com/kcl-lang/kcl/assets/22744597/b743d6b3-dcf5-4fc5-8370-3d9ad98bd050)
![image](https://github.com/kcl-lang/kcl/assets/22744597/2b1c5cf8-d393-447d-bcce-e9a599e5e364)
![image](https://github.com/kcl-lang/kcl/assets/22744597/a9327c9e-f5fd-4fee-a0f0-fe7f581b00b8)

+ [x] Wrong completion items for attribute in the if block.

![image](https://github.com/kcl-lang/kcl/assets/22744597/1a1c3a7a-f44d-4d10-98e5-f7397a98a708)

+ [x] Wrong completion items for attribute in the if condition.

![image](https://github.com/kcl-lang/kcl/assets/22744597/20758754-52b7-4db7-be00-139668bce894)

+ [x] No hover information for the if config block.
https://github.com/kcl-lang/kcl/pull/1018
![image](https://github.com/kcl-lang/kcl/assets/22744597/6a9f8c84-938b-4d6d-b50c-b2544644c070)

+ [x] No hover information for the internal schema scope variables that are not the schema attribute.
https://github.com/kcl-lang/kcl/pull/1014
![image](https://github.com/kcl-lang/kcl/assets/22744597/5b82e010-3e54-4ec1-a96b-cee2d6a76dfe)

+ [x] Wrong definition for the local variable in lambda
https://github.com/kcl-lang/kcl/pull/1048
```python
f = lambda a: [str], b: [str], c: [str] -> [str] {
    c + a + b # The definition of `c` is wrong
}
c = f([], [], [])
```

**Comment by Peefy** [comment]
+ [ ] The hover may not work well for the complex selector expr, e.g,. `Fib {n = 8}.value` at `samples/fib.k`

**Comment by amyXia1994** [comment]
+ [] go to definition failed in base.k (appops/guestbook/base/base.k, Line 7) Can't find ast node from position due to config merge(preprocess in resolver)

**Comment by amyXia1994** [comment]
go to definition produces more than one definitions, but only the v2 schema is the real definition.

![goto](https://github.com/KusionStack/kcl/assets/29722609/f20997b6-9940-449f-b533-7ba260c1cdb5)
