### ISSUE TITLE
[Enhancement] Unified content and style of KCL error messages.

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#527]
## Enhancement

+ [x] Singular/even numbers https://github.com/kcl-lang/kcl/issues/768
![image](https://github.com/kcl-lang/kcl/assets/22744597/875fbed6-ec1c-49ef-a6f0-94f66fc00497)

takes 2 argument -> takes 2 arguments

+ [x] Show function type error message e.g. `(int, int) -> int` instead of `function` https://github.com/kcl-lang/kcl/issues/770

```python
_func = lambda x: int, y: int -> int {
    x - y
}  # Ok
_func = lambda x: int, y: int -> str {
    str(x + y)
}  # Error: function (int, int) -> str can't be assigned to function (int, int) -> int
```

+ [x] Inconsistent error display between IDE and CLI https://github.com/kcl-lang/kcl/issues/776
![image](https://github.com/kcl-lang/kcl/assets/22744597/a76b9882-551d-42d0-a74e-b7716c1e33ec)
![image](https://github.com/kcl-lang/kcl/assets/22744597/2cc45d95-b04a-42f1-8699-f1bd4316d2f1)

+ [x] Keyword argument format error message enhancement https://github.com/kcl-lang/kcl/issues/775

```python
a = "{ID}".format(2) # keyword argument not found -> keyword argument 'ID' not found
```

+ [x] Enhance value union conflict error message

+ [x] Error positions for undefined lambda parameters

![image](https://github.com/kcl-lang/kcl/assets/22744597/9227ed85-f171-4ff2-89be-7bea55a03024)

+ [x] Positional argument error not found for schema

```python
schema D[name: str]: # ''
    n: str = name

d = D() { # expected 1 positional argument, found 0
    n = ""
}

```

+ [ ] Name not found in the schema expression

```python
schema Person:
    image: str
    check:
        regex.match(image, "^[a-zA-Z]+:\d+\.\d+\.\d+$"), "image name should be like 'nginx:1.14.2'" # regex package is not importted
```
