### ISSUE TITLE
[Enhancement][track]More IDE completion support on kcl attribute/parameters

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl#747]
## Enhancement

- [x] #748
- [x] #749
- [x] #750
- [x] #751
- [x] #752 
- [x] completion on the char `[` for the schema and config type, e.g.,   
> won't fix, not a static value

```python
alpha = {
    'en-US': r"^[A-Z]+$",
    'az-AZ': r"^[A-VXYZÇƏĞİıÖŞÜ]+$",
}
en_US = alpha[ # completion list 'en-US' and 'az-AZ'
```
- [x] completion for internal and external package name.
- [x] Incorrect completion list inside nested schema configuration #971 

![image](https://github.com/kcl-lang/kcl/assets/22744597/09081a35-7eb9-4b97-a688-a2a79c405add)

- [x] wrong completion for the package alias name #943 

![image](https://github.com/kcl-lang/kcl/assets/22744597/7e2e0424-685a-4511-bbf7-860a3f7b51a2)
![image](https://github.com/kcl-lang/kcl/assets/22744597/415e147c-6193-4d5a-9ace-8b8262363e1d)

- [x] wrong completion in the internal string #923 

![image](https://github.com/kcl-lang/kcl/assets/22744597/666d833e-7e66-4f4e-a351-a39f314b43ab)
